<?php

/**
 * @file
 * Code for the Culture frontend feature.
 */

include_once 'culture_frontend.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function culture_frontend_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_form_alter().
 */
function culture_frontend_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {

    // Process "tommorow".
    $tomorrow = new DateTime('tomorrow');
    $form['tomorrow'] = array(
      '#prefix' => '<div class="events-tomorrow">',
      '#suffix' => '</div>',
      '#type' => 'container',
      'tommorow' => array(
        '#type' => 'link',
        '#title' => t('Events tomorrow'),
        '#href' => url('#'),
        '#attributes' => array(
          'id' => 'events-tomorrow',
          'class' => array(
            'btn',
            'btn-success',
          ),
        ),
        '#attached' => array(
          'js' => array(
            array(
              'data' => array(
                'culture_frontend' => array(
                  'tommorow' => array(
                    'date_start' => $tomorrow->format('d-m-Y'),
                    'date_end' => $tomorrow->format('d-m-Y'),
                  ),
                ),
              ),
              'type' => 'setting',
            ),
          ),
        ),
      ),
    );

    // Process "next weekend".
    $saturday = strtotime('saturday');
    $saturday = date('d-m-Y', $saturday);

    $sunday = strtotime('sunday');
    $sunday = date('d-m-Y', $sunday);

    $form['next-weekend'] = array(
      '#prefix' => '<div class="events-next_weekend">',
      '#suffix' => '</div>',
      '#type' => 'container',
      'tommorow' => array(
        '#type' => 'link',
        '#title' => t('Events next weekend'),
        '#href' => url('#'),
        '#attributes' => array(
          'id' => 'events-next_weekend',
          'class' => array(
            'btn',
            'btn-success',
          ),
        ),
        '#attached' => array(
          'js' => array(
            array(
              'data' => array(
                'culture_frontend' => array(
                  'next_weekend' => array(
                    'date_start' => $saturday,
                    'date_end' => $sunday,
                  ),
                ),
              ),
              'type' => 'setting',
            ),
          ),
        ),
      ),
    );

    // Process "top events (sticky)".
    $form['top-events'] = array(
      '#prefix' => '<div class="top_events">',
      '#suffix' => '</div>',
      '#type' => 'container',
      'tommorow' => array(
        '#type' => 'link',
        '#title' => t('Top events'),
        '#href' => url('#'),
        '#attributes' => array(
          'id' => 'events-top_events',
          'class' => array(
            'btn',
            'btn-success',
          ),
        ),
        '#attached' => array(
          'js' => array(
            array(
              'data' => array(
                'culture_frontend' => array(
                  'top_events' => array(
                    'today' => date('d-m-Y'),
                  ),
                ),
              ),
              'type' => 'setting',
            ),
          ),
        ),
      ),
    );
  }
}

/**
 * Implements hook_page_alter().
 */
function culture_frontend_page_alter(&$page) {
  $args = arg();
  if (count($args) == 1 && $args['0'] == 'arrangementer') {
    drupal_add_js(drupal_get_path('module', 'culture_frontend') . '/js/events.culture_frontend.js', 'file');
  }
}
